---
title: "Loops and functions"
format: html
editor_options: 
  chunk_output_type: console
---

# Task 1
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

my_matrix <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
    my_matrix[i,j] <- print(paste(weekdays[i], "-", transects[j]))
  }
}
```

# Task 2
```{r}
force <- function(mass, acceleration) {
  F <- mass * acceleration
  print(paste("The resulting force is", F, "Newtons."))
}

force(5, 10)
```

# Task 3
```{r}
library(tidyverse)
fish_parms <- data.frame(sci_name = c("Chanos chanos",
                                      "Sphyraena barracuda",
                                      "Caranx ignobilis"),
                         common_name = c("Milkfish",
                                         "Great barracuda",
                                         "Giant trevally"),
                         a_est = c(0.0905,
                                   0.0181,
                                   0.0353),
                         b_est = c(2.52,
                                   3.27,
                                   3.05))


fish_weight <- function(fish_name, tot_length) {
  fish_select <- filter(fish_parms, common_name == fish_name)
  W <- fish_select$a_est * (tot_length^fish_select$b_est)
  print(W)
}

fish_weight("Great barracuda", 10)

length_vec <- seq(from = 0, to = 100, by = 1)
milkfish_weights <- fish_weight("Milkfish", length_vec)
```

# Task 4

```{r}
wave_power <- function(height, period) {
  P <- 0.5 * (height^2) * period 
  print(P)
}

wave_height_vec <- seq(from = 0, to = 3, by = 0.2)
wave_power(wave_height_vec, 8)
```

# Task 5 (optional)

```{r}
approx_wave_power <- function(depth, height, period) {
  
  if (depth < 0) {
    stop("depth cannot be a negative number")
  }
  
  if (depth > 12) {
    
    message("depth > 12, deep water equation used")
    
    print(0.5 * (height^2) * period)
    
  } else if (depth <= 12) {
    
    message("depth <= 12, shallow water equation used")
    
    print(0.81 * (height^2) * period)
  }
}

approx_wave_power(depth = -2, height = 1, period = 1)
  
```












